# Generated by Django 5.2.3 on 2025-06-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title', '-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
