# Generated by Django 5.2.3 on 2025-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='post',
            field=models.CharField(choices=[('UK', 'UrkPost'), ('NW', 'NewPost')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('card', 'Card'), ('delivery', 'Delivery')]),
        ),
    ]
