# Generated by Django 5.2.3 on 2025-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_address_order_post_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('card', 'Card'), ('delivery', 'Delivery')], default='card'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post',
            field=models.CharField(choices=[('UK', 'UrkPost'), ('NW', 'NewPost')], default='NW'),
        ),
    ]
