# Generated by Django 5.2.3 on 2025-07-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('card', 'Card'), ('delivery', 'Delivery')], default='card'),
        ),
    ]
