# Generated by Django 5.2.3 on 2025-07-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payable',
            field=models.BooleanField(default=False),
        ),
    ]
